const images = {
  icon: require("../assets/icon-small.png"),
  logos: {
    branded: {
      google: require("./logos/branded/google.png"),
      microsoft: require("./logos/branded/microsoft.png"),
      paypal: require("./logos/branded/paypal.png"),
      discord: require("./logos/branded/discord.png"),
      github: require("./logos/branded/github.png"),
      instagram: require("./logos/branded/instagram.png"),
      twitter: require("./logos/branded/twitter.png"),
      amazon: require("./logos/branded/amazon.png"),
      facebook: require("./logos/branded/facebook.png"),
      reddit: require("./logos/branded/reddit.png"),
      netflix: require("./logos/branded/netflix.png"),
      twitch: require("./logos/branded/twitch.png"),
    },
    letters: {
      a: require("./logos/letters/a.png"),
      b: require("./logos/letters/b.png"),
      c: require("./logos/letters/c.png"),
      d: require("./logos/letters/d.png"),
      e: require("./logos/letters/e.png"),
      f: require("./logos/letters/f.png"),
      g: require("./logos/letters/g.png"),
      h: require("./logos/letters/h.png"),
      i: require("./logos/letters/i.png"),
      j: require("./logos/letters/j.png"),
      k: require("./logos/letters/k.png"),
      l: require("./logos/letters/l.png"),
      m: require("./logos/letters/m.png"),
      n: require("./logos/letters/n.png"),
      o: require("./logos/letters/o.png"),
      p: require("./logos/letters/p.png"),
      q: require("./logos/letters/q.png"),
      r: require("./logos/letters/r.png"),
      s: require("./logos/letters/s.png"),
      t: require("./logos/letters/t.png"),
      u: require("./logos/letters/u.png"),
      v: require("./logos/letters/v.png"),
      w: require("./logos/letters/w.png"),
      x: require("./logos/letters/x.png"),
      y: require("./logos/letters/y.png"),
      z: require("./logos/letters/z.png"),
    },
    default: require("../assets/icon.png")
  }
}

export default images;